stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree:           false
            timestampable:  true
            blameable:      true
            sluggable:      false
            softdeleteable: false
            uploadable:     false