imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: bundles/ }
    - { resource: resources/ }

parameters:
    locale: en

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"