app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_app_sylious:
    resource: "routings/project.yml"
    prefix:   /

rbs_security:
    resource: "@RbsSecurityBundle/Resources/config/routing.yml"
    prefix:   /